# Social links
email = "example@gmail.com"
twitter = "GoHugoIO"
github = "y1zhou"
google_scholar = "yxUduqMAAAAJ"  # Michael Jordan
linkedin = "satyanadella"  # Satya Nadella
# Code highlighting
highlight_enabled = true
hljs_version = "10.1.1"
hljs_languages = ["r", "javascript", "python", "bash", "go", "json"]
hljs_light_style = "github-gist"
hljs_dark_style = "atom-one-dark-reasonable"
