theme = "hugo-northeast"
languageCode = "en-us"
baseurl = "http://example.com/"
title = "Hugo Theme Northeast"

author = "John Doe"
copyright = "2019-{year} &copy;"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

    github_user = "dirkolbrich"
    github_repo = "https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter"
    github_banner = true

    favicon = "favicon.ico"
