title = "Hugo Northeast"
author = "John Doe"
baseurl = "http://example.com/"
languageCode = "en-us"

theme = "hugo-northeast"
enableGitInfo = true
copyright = "2019-{year} &copy;"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "dracula"
    tabWidth = 2
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = true

    github_user = "dirkolbrich"
    github_repo = "https://github.com/dirkolbrich/hugo-theme-tailwindcss-starter"
    github_banner = true

    favicon = "favicon.ico"
